### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by bthiebault** [JakobGM/astrality#142]
I have the following error message when starting astrality.

I have probably messed up with the configuration files, but the traceback message is not very helpful in identifying the source of the problem.

```
2019-05-09 13:00:39     root INFO
Using configuration file "/home/ben/.config/astrality/astrality.yml"

Traceback (most recent call last):
  File "/usr/bin/astrality", line 101, in <module>
    main(modules=modules, logging_level=logging_level, dry_run=dry_run)
  File "/usr/lib/python3.7/site-packages/astrality/astrality.py", line 97, in main
    ) = user_configuration()
  File "/usr/lib/python3.7/site-packages/astrality/config.py", line 165, in user_configuration
    context=Context(),
  File "/usr/lib/python3.7/site-packages/astrality/utils.py", line 184, in compile_yaml
    return load(StringIO(config_string), Loader=Loader)
  File "/usr/lib/python3.7/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a block mapping
  in "<file>", line 54, column 9
did not find expected key
  in "<file>", line 56, column 13
```

Here is the content of my base configuration file:

```
 cat astrality.yml
astrality:
    # If hot_reload_config is enabled, modifications to this file automatically
    # runs:
    #       1) exit actions from the old configuration
    #       2) startup actions from the new configuration
    # Requires restart if enabled
    hot_reload_config: true

    # You can delay astrality on startup. The delay is given in seconds.
    startup_delay: 0


modules:
    # Modules can require successfull shell commands (non-zero exit codes) in
    # order to be enabled. You can specify the timeout for such checks, given
    # in seconds.
    requires_timeout: 1

    # Astrality can wait for shell commands to complete in their specified
    # order. You can set the number of seconds Astrality waits for the shell
    # commands to exit.
    run_timeout: 0

    # Modified templates can be automatically recompiled. This also includes
    # files that have been copied to a target destination.
    reprocess_modified_files: true

    # There are two possible ways to define modules. Either in this file, as
    # shown further below, or in separate external module directories within the
    # following specified directory, relatively interpreted as:
    # $ASTRALITY_CONFIG_HOME/modules
    modules_directory: modules

    # You enable modules by specifying the <name> of each module.
    # Modules defined in <modules_directory>/<subdirectory>/config.yml are
    # enabled by writing name: <subdirectory>::<name>
    #
    # '*' enables all modules in this file, '*::*' enables all modules defined
    # in subdirectories of <modules_directory>.
    enabled_modules:
        # Module defined in this file
        - name: polybar::*
        - name: bspwm::*
        - name: kitty::*

        # All modules defined in <modules_directory>/solar_desktop/config.yml
        - name: solar_desktop::*

        # Module defined at https://github.com/jakobgm/color-schemes.astrality
        - name: github::jakobgm/color-schemes.astrality
          autoupdate: true  # Fetch new color schemes as they are added
```

**Comment by bthiebault** [comment]
I found what the problem was.

Some extra spaces where inserted in my context.yml file.
