### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by sshashank124** [JakobGM/astrality#34]
Getting the following error when running astrality:

```
2018-05-10 15:05:47 astrality.compiler INFO [Compiling] Template: "/home/phaqlow/.config/astrality/modules/vcs/git/t.gitconfig" -> Target: "/home/phaqlow/.gitconfig"
Traceback (most recent call last):
  File "/usr/bin/astrality", line 67, in <module>
    main(modules=modules, logging_level=logging_level, dry_run=dry_run)
  File "/usr/lib/python3.6/site-packages/astrality/astrality.py", line 111, in main
    module_manager.finish_tasks()
  File "/usr/lib/python3.6/site-packages/astrality/module.py", line 560, in finish_tasks
    self.startup()
  File "/usr/lib/python3.6/site-packages/astrality/module.py", line 645, in startup
    self.execute(action='all', block='on_startup')
  File "/usr/lib/python3.6/site-packages/astrality/module.py", line 635, in execute
    dry_run=self.dry_run,
  File "/usr/lib/python3.6/site-packages/astrality/module.py", line 280, in execute
    results = getattr(action_block, action)(dry_run=dry_run)
  File "/usr/lib/python3.6/site-packages/astrality/actions.py", line 866, in run
    dry_run=dry_run,
  File "/usr/lib/python3.6/site-packages/astrality/actions.py", line 643, in execute
    command = self.option(key='shell')
  File "/usr/lib/python3.6/site-packages/astrality/actions.py", line 114, in option
    option_value = self._options.get(key, default)
AttributeError: 'str' object has no attribute 'get'
```

This happens after all the modules are done processing. Checked and `_options` is indeed a `Union` of `Dict` so not sure why this is happening?

**Comment by sshashank124** [comment]
Never mind, issue was on my end. I hadn't updated my astrality config to use the new `shell` option under the `run` action block
